import Head from 'next/head'
import Cadastro from './Components/Cadastro'

export default function Home() 
{
  return (
    <>
      <Head>
        <title>Chat_Real-Time</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Cadastro/>

    </>
  )
}
